# Generated by Django 5.2.3 on 2025-06-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('links', models.URLField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_following', models.BooleanField(default=False)),
                ('is_followed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_verified_email', models.BooleanField(default=False)),
                ('is_verified_phone', models.BooleanField(default=False)),
                ('is_verified_identity', models.BooleanField(default=False)),
                ('is_verified_address', models.BooleanField(default=False)),
                ('is_verified_document', models.BooleanField(default=False)),
                ('is_verified_profile', models.BooleanField(default=False)),
                ('is_verified_account', models.BooleanField(default=False)),
                ('is_verified_payment', models.BooleanField(default=False)),
                ('is_verified_subscription', models.BooleanField(default=False)),
                ('is_verified_membership', models.BooleanField(default=False)),
                ('is_verified_subscription_plan', models.BooleanField(default=False)),
                ('is_verified_payment_method', models.BooleanField(default=False)),
                ('is_verified_transaction', models.BooleanField(default=False)),
                ('is_verified_order', models.BooleanField(default=False)),
                ('is_verified_review', models.BooleanField(default=False)),
                ('is_verified_rating', models.BooleanField(default=False)),
                ('is_verified_comment', models.BooleanField(default=False)),
                ('is_verified_feedback', models.BooleanField(default=False)),
                ('is_verified_notification', models.BooleanField(default=False)),
                ('is_verified_message', models.BooleanField(default=False)),
                ('is_verified_chat', models.BooleanField(default=False)),
                ('is_verified_group', models.BooleanField(default=False)),
                ('is_verified_event', models.BooleanField(default=False)),
                ('is_verified_post', models.BooleanField(default=False)),
                ('is_verified_story', models.BooleanField(default=False)),
                ('is_verified_media', models.BooleanField(default=False)),
                ('is_verified_file', models.BooleanField(default=False)),
                ('is_verified_link', models.BooleanField(default=False)),
                ('is_verified_image', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
